// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module data_redir_m_projection_odd_m (
        ap_ready,
        input_lo,
        input_mi,
        input_hi,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6
);


output   ap_ready;
input  [31:0] input_lo;
input  [31:0] input_mi;
input  [7:0] input_hi;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;

wire   [7:0] triangle_3d_z0_V_fu_64_p4;
wire   [7:0] mul_ln1364_fu_122_p0;
wire   [9:0] mul_ln1364_fu_122_p1;
wire   [16:0] mul_ln1364_fu_122_p2;
wire   [6:0] tmp_fu_128_p4;
wire   [7:0] triangle_3d_z1_V_fu_88_p4;
wire   [7:0] mul_ln1364_1_fu_146_p0;
wire   [9:0] mul_ln1364_1_fu_146_p1;
wire   [16:0] mul_ln1364_1_fu_146_p2;
wire   [6:0] tmp_1_fu_152_p4;
wire   [7:0] mul_ln1364_2_fu_170_p0;
wire   [9:0] mul_ln1364_2_fu_170_p1;
wire   [16:0] mul_ln1364_2_fu_170_p2;
wire   [6:0] tmp_2_fu_176_p4;
wire   [7:0] zext_ln1364_1_fu_138_p1;
wire   [7:0] zext_ln1364_5_fu_186_p1;
wire   [7:0] add_ln213_fu_190_p2;
wire   [7:0] zext_ln1364_3_fu_162_p1;
wire   [7:0] triangle_3d_x0_V_fu_50_p1;
wire   [7:0] triangle_3d_y1_V_fu_84_p1;
wire   [7:0] add_ln213_1_fu_196_p2;
wire   [16:0] mul_ln1364_1_fu_146_p00;
wire   [16:0] mul_ln1364_2_fu_170_p00;
wire   [16:0] mul_ln1364_fu_122_p00;

data_redir_m_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U1(
    .din0(mul_ln1364_fu_122_p0),
    .din1(mul_ln1364_fu_122_p1),
    .dout(mul_ln1364_fu_122_p2)
);

data_redir_m_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U2(
    .din0(mul_ln1364_1_fu_146_p0),
    .din1(mul_ln1364_1_fu_146_p1),
    .dout(mul_ln1364_1_fu_146_p2)
);

data_redir_m_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U3(
    .din0(mul_ln1364_2_fu_170_p0),
    .din1(mul_ln1364_2_fu_170_p1),
    .dout(mul_ln1364_2_fu_170_p2)
);

assign add_ln213_1_fu_196_p2 = (add_ln213_fu_190_p2 + zext_ln1364_3_fu_162_p1);

assign add_ln213_fu_190_p2 = (zext_ln1364_1_fu_138_p1 + zext_ln1364_5_fu_186_p1);

assign ap_ready = 1'b1;

assign ap_return_0 = triangle_3d_x0_V_fu_50_p1;

assign ap_return_1 = {{input_lo[15:8]}};

assign ap_return_2 = {{input_lo[31:24]}};

assign ap_return_3 = triangle_3d_y1_V_fu_84_p1;

assign ap_return_4 = {{input_mi[23:16]}};

assign ap_return_5 = {{input_mi[31:24]}};

assign ap_return_6 = add_ln213_1_fu_196_p2;

assign mul_ln1364_1_fu_146_p0 = mul_ln1364_1_fu_146_p00;

assign mul_ln1364_1_fu_146_p00 = triangle_3d_z1_V_fu_88_p4;

assign mul_ln1364_1_fu_146_p1 = 17'd342;

assign mul_ln1364_2_fu_170_p0 = mul_ln1364_2_fu_170_p00;

assign mul_ln1364_2_fu_170_p00 = input_hi;

assign mul_ln1364_2_fu_170_p1 = 17'd342;

assign mul_ln1364_fu_122_p0 = mul_ln1364_fu_122_p00;

assign mul_ln1364_fu_122_p00 = triangle_3d_z0_V_fu_64_p4;

assign mul_ln1364_fu_122_p1 = 17'd342;

assign tmp_1_fu_152_p4 = {{mul_ln1364_1_fu_146_p2[16:10]}};

assign tmp_2_fu_176_p4 = {{mul_ln1364_2_fu_170_p2[16:10]}};

assign tmp_fu_128_p4 = {{mul_ln1364_fu_122_p2[16:10]}};

assign triangle_3d_x0_V_fu_50_p1 = input_lo[7:0];

assign triangle_3d_y1_V_fu_84_p1 = input_mi[7:0];

assign triangle_3d_z0_V_fu_64_p4 = {{input_lo[23:16]}};

assign triangle_3d_z1_V_fu_88_p4 = {{input_mi[15:8]}};

assign zext_ln1364_1_fu_138_p1 = tmp_fu_128_p4;

assign zext_ln1364_3_fu_162_p1 = tmp_1_fu_152_p4;

assign zext_ln1364_5_fu_186_p1 = tmp_2_fu_176_p4;

endmodule //data_redir_m_projection_odd_m
